//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryT
    {
        public CountryT()
        {
            this.StateTs = new HashSet<StateT>();
        }
    
        public string Country { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> GeoID { get; set; }
        public string Country3 { get; set; }
        public Nullable<int> ReleaseNo { get; set; }
    
        public virtual ReleaseT ReleaseT { get; set; }
        public virtual Geocode2T Geocode2T { get; set; }
        public virtual ICollection<StateT> StateTs { get; set; }
    }
}
