//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIVISIONT
    {
        public DIVISIONT()
        {
            this.TransLogTs = new HashSet<TransLogT>();
            this.ExemptionClassTs = new HashSet<ExemptionClassT>();
            this.TaxabilityOverrideTs = new HashSet<TaxabilityOverrideT>();
        }
    
        public int DivisionSurrogate { get; set; }
        public string DIVISION_ID { get; set; }
        public string ACOPDS { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string Plus4 { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> EntitySurrogate { get; set; }
    
        public virtual ENTITYT ENTITYT { get; set; }
        public virtual ICollection<TransLogT> TransLogTs { get; set; }
        public virtual ProductItemT ProductItemT { get; set; }
        public virtual ICollection<ExemptionClassT> ExemptionClassTs { get; set; }
        public virtual ICollection<TaxabilityOverrideT> TaxabilityOverrideTs { get; set; }
    }
}
