//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTITYT
    {
        public ENTITYT()
        {
            this.DIVISIONTs = new HashSet<DIVISIONT>();
            this.ProductGroupTs = new HashSet<ProductGroupT>();
            this.TaxAuthorityTaxTs = new HashSet<TaxAuthorityTaxT>();
        }
    
        public string ACORDS { get; set; }
        public int EntitySurrogate { get; set; }
        public string ENTITY_ID { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string Plus4 { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public Nullable<int> ItemID { get; set; }
    
        public virtual ICollection<DIVISIONT> DIVISIONTs { get; set; }
        public virtual ProductItemT ProductItemT { get; set; }
        public virtual ICollection<ProductGroupT> ProductGroupTs { get; set; }
        public virtual ICollection<TaxAuthorityTaxT> TaxAuthorityTaxTs { get; set; }
    }
}
