//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geocode1T
    {
        public Nullable<int> GeoID { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public string City { get; set; }
        public string TaxDistrictDescription { get; set; }
        public string ActualGeoCodeDefault { get; set; }
        public Nullable<int> PartOf { get; set; }
        public string GNIScode { get; set; }
        public Nullable<int> ExpReleaseNo { get; set; }
        public int ReleaseNo { get; set; }
    
        public virtual ReleaseT ReleaseT { get; set; }
        public virtual Geocode2T Geocode2T { get; set; }
        public virtual StateT StateT { get; set; }
    }
}
