//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geocode2T
    {
        public Geocode2T()
        {
            this.Geocode1T = new HashSet<Geocode1T>();
            this.TaxJurisdictionTs = new HashSet<TaxJurisdictionT>();
            this.CountryTs = new HashSet<CountryT>();
            this.StateTs = new HashSet<StateT>();
        }
    
        public int GeoID { get; set; }
        public string ActualGeoCode { get; set; }
        public Nullable<int> ReleaseNo { get; set; }
    
        public virtual ICollection<Geocode1T> Geocode1T { get; set; }
        public virtual ReleaseT ReleaseT { get; set; }
        public virtual ICollection<TaxJurisdictionT> TaxJurisdictionTs { get; set; }
        public virtual ICollection<CountryT> CountryTs { get; set; }
        public virtual ICollection<StateT> StateTs { get; set; }
    }
}
