//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItemT
    {
        public ProductItemT()
        {
            this.DIVISIONTs = new HashSet<DIVISIONT>();
            this.ENTITYTs = new HashSet<ENTITYT>();
        }
    
        public int ItemID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string Item { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<System.DateTime> LEGALEFFECTIVEDATE { get; set; }
        public Nullable<System.DateTime> LEGALEXPIRATIONDATE { get; set; }
        public Nullable<int> ReleaseNo { get; set; }
    
        public virtual ICollection<DIVISIONT> DIVISIONTs { get; set; }
        public virtual ICollection<ENTITYT> ENTITYTs { get; set; }
        public virtual ProductGroupT ProductGroupT { get; set; }
    }
}
