//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGroupT
    {
        public ProductGroupT()
        {
            this.ProductItemTs = new HashSet<ProductItemT>();
        }
    
        public int GroupID { get; set; }
        public string ProductGroup { get; set; }
        public string GroupDescription { get; set; }
        public Nullable<System.DateTime> LEGALEFFECTIVEDATE { get; set; }
        public Nullable<System.DateTime> LEGALEXPIRATIONDATE { get; set; }
        public Nullable<int> ReleaseNo { get; set; }
        public Nullable<int> EntitySurrogate { get; set; }
    
        public virtual ENTITYT ENTITYT { get; set; }
        public virtual ICollection<ProductItemT> ProductItemTs { get; set; }
    }
}
