//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateT
    {
        public StateT()
        {
            this.Geocode1T = new HashSet<Geocode1T>();
            this.TaxabilityStateTs = new HashSet<TaxabilityStateT>();
        }
    
        public string Country { get; set; }
        public string State { get; set; }
        public string StateName { get; set; }
        public Nullable<int> GeoID { get; set; }
        public Nullable<int> ReleaseNo { get; set; }
    
        public virtual CountryT CountryT { get; set; }
        public virtual ICollection<Geocode1T> Geocode1T { get; set; }
        public virtual Geocode2T Geocode2T { get; set; }
        public virtual ReleaseT ReleaseT { get; set; }
        public virtual ICollection<TaxabilityStateT> TaxabilityStateTs { get; set; }
    }
}
