//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxAuthorityT
    {
        public TaxAuthorityT()
        {
            this.TaxAuthorityTaxTs = new HashSet<TaxAuthorityTaxT>();
        }
    
        public int TaxAuthorityID { get; set; }
        public string TaxAuthorityName { get; set; }
        public string TaxAuthType { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public Nullable<int> ReleaseNo { get; set; }
    
        public virtual ReleaseT ReleaseT { get; set; }
        public virtual ICollection<TaxAuthorityTaxT> TaxAuthorityTaxTs { get; set; }
    }
}
