//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxabilityOverrideT
    {
        public int RuleID { get; set; }
        public int DivisionSurrogate { get; set; }
        public System.DateTime CustomerEffectiveDate { get; set; }
        public Nullable<System.DateTime> CustomerExpirationDate { get; set; }
        public string TaxRuleType { get; set; }
        public string DESCRIPTION { get; set; }
        public string TaxAuthType { get; set; }
        public Nullable<int> TaxAuthorityID { get; set; }
        public string TaxType { get; set; }
        public string TaxCat { get; set; }
        public Nullable<int> GeoID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string TAXABLE { get; set; }
        public Nullable<decimal> PercentTaxable { get; set; }
        public string TransactionType { get; set; }
    
        public virtual DIVISIONT DIVISIONT { get; set; }
    }
}
