//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxJurisdictionT
    {
        public int TaxID { get; set; }
        public int GeoID { get; set; }
        public System.DateTime LEGALEFFECTIVEDATE { get; set; }
        public int ReleaseNo { get; set; }
        public Nullable<int> BasicTaxOverrideID { get; set; }
        public Nullable<int> CalcTaxOverrideID { get; set; }
        public Nullable<int> ReportingTaxOverrideID { get; set; }
        public Nullable<System.DateTime> LEGALEXPIRATIONDATE { get; set; }
    
        public virtual Geocode2T Geocode2T { get; set; }
        public virtual ReleaseT ReleaseT { get; set; }
        public virtual TaxAuthorityTaxT TaxAuthorityTaxT { get; set; }
        public virtual TaxOverrideReasonT TaxOverrideReasonT { get; set; }
        public virtual TaxOverrideReasonT TaxOverrideReasonT1 { get; set; }
        public virtual TaxOverrideReasonT TaxOverrideReasonT2 { get; set; }
    }
}
