//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxRateT
    {
        public TaxRateT()
        {
            this.TransItemTaxTs = new HashSet<TransItemTaxT>();
        }
    
        public int TaxRateID { get; set; }
        public Nullable<int> CalcDataID { get; set; }
        public Nullable<int> Tier { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public Nullable<decimal> MinTaxBase { get; set; }
        public Nullable<decimal> MaxTaxBase { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<decimal> MinUnitBase { get; set; }
        public Nullable<decimal> MaxUnitBase { get; set; }
        public Nullable<int> ReleaseNo { get; set; }
    
        public virtual ReleaseT ReleaseT { get; set; }
        public virtual ICollection<TransItemTaxT> TransItemTaxTs { get; set; }
    }
}
