//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxTypeT
    {
        public string TaxType { get; set; }
        public string TaxTypeDescription { get; set; }
        public Nullable<int> ReleaseNo { get; set; }
    
        public virtual ReleaseT ReleaseT { get; set; }
    }
}
