//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransTaxOnTaxT
    {
        public long TransactionID { get; set; }
        public int LineItemID { get; set; }
        public int TaxID { get; set; }
        public int TaxRateID { get; set; }
        public long ContributingTransactionID { get; set; }
        public int ContributingLineItemID { get; set; }
        public int CONTRIBUTING_TAXID { get; set; }
        public int CONTRIBUTING_TAXRATEID { get; set; }
        public Nullable<decimal> TaxableTaxAmount3 { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
    
        public virtual TransItemTaxT TransItemTaxT { get; set; }
    }
}
