//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransItemT
    {
        public TransItemT()
        {
            this.TransItemTaxTs = new HashSet<TransItemTaxT>();
        }
    
        public long TransactionID { get; set; }
        public int LineItemID { get; set; }
        public string UsrLineItemID { get; set; }
        public string SKUID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> AvgUnitPrice { get; set; }
        public Nullable<decimal> LineItemAmount { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string CLASSCODE { get; set; }
        public Nullable<int> NXSShipToGeoID { get; set; }
        public Nullable<int> NXSShipFromGeoID { get; set; }
        public Nullable<int> OrderPlacementGeoID { get; set; }
        public Nullable<int> OrderApprovalGeoID { get; set; }
        public Nullable<int> LocationSurrogate { get; set; }
        public string DataString { get; set; }
        public Nullable<int> OrderApprovalAddressId { get; set; }
        public Nullable<int> OrderPlacementAddressId { get; set; }
        public Nullable<int> ShipFromAddressId { get; set; }
        public Nullable<int> ShipToAddressId { get; set; }
    
        public virtual TransItemAT TransItemAT { get; set; }
        public virtual TransLogT TransLogT { get; set; }
        public virtual ICollection<TransItemTaxT> TransItemTaxTs { get; set; }
    }
}
