//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionInvoiceMappingT
    {
        public long TransactionId { get; set; }
        public string InvoicePath { get; set; }
        public int TransactionInvoiceMappingSurrogate { get; set; }
    }
}
