//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransLog1
    {
        public long TransactionID { get; set; }
        public Nullable<int> DivisionSurrogate { get; set; }
        public string InvoiceID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string SourceSystem { get; set; }
        public Nullable<short> TransactionStatus { get; set; }
        public string TransactionType { get; set; }
        public string LiabilityType { get; set; }
        public string TestTransaction { get; set; }
        public Nullable<int> NXSShipToGeoID { get; set; }
        public string CT39oA { get; set; }
        public Nullable<int> NXSShipFromGeoID { get; set; }
        public string CT39pA { get; set; }
        public Nullable<int> OrderPlacementGeoID { get; set; }
        public string CT39qA { get; set; }
        public Nullable<int> OrderApprovalGeoID { get; set; }
        public string CT39rA { get; set; }
        public string SitusSolicitedOutside { get; set; }
        public string SitusCanRejectDelivery { get; set; }
        public string SitusFOB { get; set; }
        public string SitusMailOrder { get; set; }
        public string SitusDeliveryBy { get; set; }
        public string SitusShipFromPOB { get; set; }
        public string CustomerID { get; set; }
        public string Customer { get; set; }
        public string Provider { get; set; }
        public Nullable<long> OriginalTransactionID { get; set; }
        public Nullable<int> SUID { get; set; }
        public string APPLICATION_LOGIN_ID { get; set; }
        public string TransactionDescription { get; set; }
        public Nullable<System.DateTime> TSINS { get; set; }
        public Nullable<System.DateTime> TSCHG { get; set; }
        public Nullable<int> OrderApprovalAddressId { get; set; }
        public Nullable<int> OrderPlacementAddressId { get; set; }
        public Nullable<int> ShipFromAddressId { get; set; }
        public Nullable<int> ShipToAddressId { get; set; }
        public string TransactionReturnStatus { get; set; }
    }
}
