//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransItemTax2
    {
        public long TransactionID { get; set; }
        public int LineItemID { get; set; }
        public int TaxID { get; set; }
        public Nullable<int> TaxAuthorityID { get; set; }
        public string TaxAuthorityName { get; set; }
        public string TaxAuthType { get; set; }
        public string TaxType { get; set; }
        public string TaxCat { get; set; }
        public int TaxRateID { get; set; }
        public Nullable<int> Tier { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<int> CalcDataID { get; set; }
        public string CONTRIBUTE { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<decimal> ExemptTaxableAmt { get; set; }
        public Nullable<decimal> NonTaxableAmt { get; set; }
        public Nullable<decimal> TaxableQuantity { get; set; }
        public Nullable<decimal> ExemptTaxableQty { get; set; }
        public Nullable<decimal> NonTaxableQty { get; set; }
        public Nullable<decimal> TaxApplied3 { get; set; }
        public Nullable<decimal> FeeApplied3 { get; set; }
        public Nullable<decimal> TaxableTaxAmount3 { get; set; }
        public string CT39zA { get; set; }
        public string Situs { get; set; }
        public string CustomTransInfo { get; set; }
        public string NonTaxReason { get; set; }
        public Nullable<int> CEMCertificateID { get; set; }
    }
}
