//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransErrorLogT
    {
        public int ErrorLogID { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public Nullable<int> ErrorClass { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public string ErrorShortMessage { get; set; }
        public string ErrorLevel { get; set; }
        public string ErrorLongMessage { get; set; }
        public string UsrLineItemID { get; set; }
        public Nullable<System.DateTime> TSINS { get; set; }
    }
}
