//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransItemAT
    {
        public long TransactionID { get; set; }
        public int LineItemID { get; set; }
        public string ProductGroup { get; set; }
        public string Item { get; set; }
        public string UserData { get; set; }
        public string TransactionType { get; set; }
        public string Customer { get; set; }
        public string Provider { get; set; }
        public string SitusSolicitedOutside { get; set; }
        public string SitusCanRejectDelivery { get; set; }
        public string SitusFOB { get; set; }
        public string SitusMailOrder { get; set; }
        public string SitusDeliveryBy { get; set; }
        public string SitusShipFromPOB { get; set; }
        public Nullable<int> OriginalLineItemID { get; set; }
    
        public virtual TransItemT TransItemT { get; set; }
    }
}
