//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.TaxFormalizer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERPROFILET
    {
        public USERPROFILET()
        {
            this.TransLogTs = new HashSet<TransLogT>();
        }
    
        public int SUID { get; set; }
        public string APPLICATION_LOGIN_ID { get; set; }
        public string PWDCNL { get; set; }
        public string ACUSER { get; set; }
        public string ACFNAM { get; set; }
        public string ACMNAM { get; set; }
        public string ACLNAM { get; set; }
        public Nullable<System.DateTime> ACPEDT { get; set; }
        public Nullable<System.DateTime> ACPXDT { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<decimal> ACUPPD { get; set; }
        public Nullable<System.DateTime> ACPCDT { get; set; }
        public string ACALYWSLOG { get; set; }
        public string PHONE { get; set; }
        public string PhExt { get; set; }
        public string EMAIL { get; set; }
        public string SecurityStamp { get; set; }
        public string UserName { get; set; }
        public bool IsLocked { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<TransLogT> TransLogTs { get; set; }
    }
}
